// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtcHFkSKiOEhqYIqL27XwrxPHIoX63GfM',
    appId: '1:950568327685:web:ee9d5a2c8d70ca28abda6c',
    messagingSenderId: '950568327685',
    projectId: 'scholarly-project',
    authDomain: 'scholarly-project.firebaseapp.com',
    storageBucket: 'scholarly-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDowy23EqrXOUC-V8CN0TTEbBXl2sdF_EI',
    appId: '1:950568327685:android:534b7d7db106a15dabda6c',
    messagingSenderId: '950568327685',
    projectId: 'scholarly-project',
    storageBucket: 'scholarly-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT0mOLajt3MPnY_lrPKeplpQJAfYvb8T0',
    appId: '1:950568327685:ios:2a0a64ab38c430daabda6c',
    messagingSenderId: '950568327685',
    projectId: 'scholarly-project',
    storageBucket: 'scholarly-project.firebasestorage.app',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT0mOLajt3MPnY_lrPKeplpQJAfYvb8T0',
    appId: '1:950568327685:ios:2a0a64ab38c430daabda6c',
    messagingSenderId: '950568327685',
    projectId: 'scholarly-project',
    storageBucket: 'scholarly-project.firebasestorage.app',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtcHFkSKiOEhqYIqL27XwrxPHIoX63GfM',
    appId: '1:950568327685:web:6c538d13b430f6e0abda6c',
    messagingSenderId: '950568327685',
    projectId: 'scholarly-project',
    authDomain: 'scholarly-project.firebaseapp.com',
    storageBucket: 'scholarly-project.firebasestorage.app',
  );

}